### PR TITLE
Make Noarch

### PR DESCRIPTION
**Pull request by BastianZim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR makes this package noarch.

### CODE REVIEW

**Comment by andrew-mcgrath** [comment]
@BastianZim I'm not familiar with the transition to a noarch package.  Do you have a link for the recommended transition?  The build check for CircleCi seems to be the only true failure at this point (🐍 3.11 support will have caused a need to rebase)

**Comment by BastianZim** [comment]
Hi @andrew-mcgrath sure, noarch packages are explained here: https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python but the overall discussion is in https://github.com/conda-forge/conda-forge.github.io/issues/1840 if you have more questions. 

CircleCI can be ignored, that is just a leftover from before. Hopefully a bot can come by at some point.

**Comment by BastianZim** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
Webhook deleted here too.

**Comment by BastianZim** [comment]
Thank you! Quick question: I asked in the main thread but didn't get an answer: For the potential bot/migrator to clean this up in all feedstocks, are there any examples? I'm happy to try to write one, but there is no info on how to do it.

**Comment by jaimergp** [comment]
Apparently the ghost notification won't disappear from the current PR, but should not show up in the coming ones.

Did you check this repo? I haven't written a migrator, but there are several examples: https://github.com/conda-forge/admin-migrations

I assume you need to:

1. Follow the instructions on the repo README
2. [List](https://docs.github.com/en/rest/webhooks/repos#list-repository-webhooks) the feedstock webhooks and find CircleCI matches
3. [Delete](https://docs.github.com/en/rest/webhooks/repos#delete-a-repository-webhook) the CircleCI one(s)

**Comment by andrew-mcgrath** [comment]
Merging based on conversation history of CircleCI pipeline allowed to be ignored and that it won't show up in future build references.

**Comment by BastianZim** [comment]
> Did you check this repo?

Yeah, it's just that some of the CircleCI info is not visible when you're not core. But that is a good list – thanks. Slightly busy right now but when I have a minute, I'll see if I can write something.

**Pull request merged**
